// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetTestDBListParamsOrderBy.
const (
	CreatedAt GetTestDBListParamsOrderBy = "created_at"
	DescTest  GetTestDBListParamsOrderBy = "desc_test"
	TestId    GetTestDBListParamsOrderBy = "test_id"
)

// Valid indicates whether the value is a known member of the GetTestDBListParamsOrderBy enum.
func (e GetTestDBListParamsOrderBy) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case DescTest:
		return true
	case TestId:
		return true
	default:
		return false
	}
}

// Defines values for GetTestDBListParamsOrderDir.
const (
	Asc  GetTestDBListParamsOrderDir = "asc"
	Desc GetTestDBListParamsOrderDir = "desc"
)

// Valid indicates whether the value is a known member of the GetTestDBListParamsOrderDir enum.
func (e GetTestDBListParamsOrderDir) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// ActionListAPIResponse defines model for ActionListAPIResponse.
type ActionListAPIResponse struct {
	Code    string           `json:"code"`
	Data    []ActionResponse `json:"data"`
	Message string           `json:"message"`
}

// ActionResponse defines model for ActionResponse.
type ActionResponse struct {
	ActionDesc string `json:"action_desc"`
	ActionId   int64  `json:"action_id"`
	ActionType string `json:"action_type"`
	Endpoint   string `json:"endpoint"`
}

// AssignUserRoleRequest defines model for AssignUserRoleRequest.
type AssignUserRoleRequest struct {
	RoleId int64 `json:"role_id"`
}

// AuthCredentialRequest defines model for AuthCredentialRequest.
type AuthCredentialRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AuthUserAPIResponse defines model for AuthUserAPIResponse.
type AuthUserAPIResponse struct {
	Code    string           `json:"code"`
	Data    AuthUserResponse `json:"data"`
	Message string           `json:"message"`
}

// AuthUserResponse defines model for AuthUserResponse.
type AuthUserResponse struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	FullName *string              `json:"full_name,omitempty"`
	Role     string               `json:"role"`
	UserId   openapi_types.UUID   `json:"user_id"`
	Username string               `json:"username"`
}

// CreateRoleRequest defines model for CreateRoleRequest.
type CreateRoleRequest struct {
	ActionIds *[]int64 `json:"action_ids,omitempty"`
	RoleDesc  string   `json:"role_desc"`
}

// EmptyAPIResponse defines model for EmptyAPIResponse.
type EmptyAPIResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ForgotPasswordRequest defines model for ForgotPasswordRequest.
type ForgotPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// HealthAPIResponse defines model for HealthAPIResponse.
type HealthAPIResponse struct {
	Code    string         `json:"code"`
	Data    HealthResponse `json:"data"`
	Message string         `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Env     string `json:"env"`
	Service string `json:"service"`
	Status  string `json:"status"`
}

// LoginAPIResponse defines model for LoginAPIResponse.
type LoginAPIResponse struct {
	Code    string        `json:"code"`
	Data    LoginResponse `json:"data"`
	Message string        `json:"message"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Limit      int    `json:"limit"`
	OrderBy    string `json:"order_by"`
	OrderDir   string `json:"order_dir"`
	Page       int    `json:"page"`
	Total      int64  `json:"total"`
	TotalPages int    `json:"total_pages"`
}

// ReadinessAPIResponse defines model for ReadinessAPIResponse.
type ReadinessAPIResponse struct {
	Code    string            `json:"code"`
	Data    ReadinessResponse `json:"data"`
	Message string            `json:"message"`
}

// ReadinessCheck defines model for ReadinessCheck.
type ReadinessCheck struct {
	Message *string `json:"message,omitempty"`
	Status  string  `json:"status"`
}

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Checks map[string]ReadinessCheck `json:"checks"`
	Status string                    `json:"status"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"full_name"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// ResendVerificationRequest defines model for ResendVerificationRequest.
type ResendVerificationRequest struct {
	Email openapi_types.Email `json:"email"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Code        string              `json:"code"`
	Email       openapi_types.Email `json:"email"`
	NewPassword string              `json:"new_password"`
}

// RoleAPIResponse defines model for RoleAPIResponse.
type RoleAPIResponse struct {
	Code    string       `json:"code"`
	Data    RoleResponse `json:"data"`
	Message string       `json:"message"`
}

// RoleResponse defines model for RoleResponse.
type RoleResponse struct {
	ActionIds *[]int64          `json:"action_ids,omitempty"`
	Actions   *[]ActionResponse `json:"actions,omitempty"`
	IsActive  bool              `json:"is_active"`
	RoleDesc  string            `json:"role_desc"`
	RoleId    int64             `json:"role_id"`
}

// SetRoleActionsRequest defines model for SetRoleActionsRequest.
type SetRoleActionsRequest struct {
	ActionIds []int64 `json:"action_ids"`
}

// TestDBAPIResponse defines model for TestDBAPIResponse.
type TestDBAPIResponse struct {
	Code    string         `json:"code"`
	Data    TestDBResponse `json:"data"`
	Message string         `json:"message"`
}

// TestDBListResponse defines model for TestDBListResponse.
type TestDBListResponse struct {
	Code    string           `json:"code"`
	Data    []TestDBResponse `json:"data"`
	Message string           `json:"message"`
	Meta    PaginationMeta   `json:"meta"`
}

// TestDBRequest defines model for TestDBRequest.
type TestDBRequest struct {
	DescTest *string `json:"desc_test,omitempty"`
}

// TestDBResponse defines model for TestDBResponse.
type TestDBResponse struct {
	CreatedAt time.Time           `json:"created_at"`
	CreatedBy *openapi_types.UUID `json:"created_by,omitempty"`
	DescTest  *string             `json:"desc_test,omitempty"`
	TestId    openapi_types.UUID  `json:"test_id"`
}

// UpdateRoleRequest defines model for UpdateRoleRequest.
type UpdateRoleRequest struct {
	ActionIds *[]int64 `json:"action_ids,omitempty"`
	IsActive  *bool    `json:"is_active,omitempty"`
	RoleDesc  *string  `json:"role_desc,omitempty"`
}

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetTestDBListParams defines parameters for GetTestDBList.
type GetTestDBListParams struct {
	// Page Page number, starts from 1.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of rows per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// OrderBy Column used for sorting.
	OrderBy *GetTestDBListParamsOrderBy `form:"order_by,omitempty" json:"order_by,omitempty"`

	// OrderDir Sort direction.
	OrderDir *GetTestDBListParamsOrderDir `form:"order_dir,omitempty" json:"order_dir,omitempty"`
}

// GetTestDBListParamsOrderBy defines parameters for GetTestDBList.
type GetTestDBListParamsOrderBy string

// GetTestDBListParamsOrderDir defines parameters for GetTestDBList.
type GetTestDBListParamsOrderDir string

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = ForgotPasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = AuthCredentialRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody = ResendVerificationRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = CreateRoleRequest

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = UpdateRoleRequest

// SetRoleActionsJSONRequestBody defines body for SetRoleActions for application/json ContentType.
type SetRoleActionsJSONRequestBody = SetRoleActionsRequest

// CreateTestDBJSONRequestBody defines body for CreateTestDB for application/json ContentType.
type CreateTestDBJSONRequestBody = TestDBRequest

// UpdateTestDBJSONRequestBody defines body for UpdateTestDB for application/json ContentType.
type UpdateTestDBJSONRequestBody = TestDBRequest

// AssignUserRoleJSONRequestBody defines body for AssignUserRole for application/json ContentType.
type AssignUserRoleJSONRequestBody = AssignUserRoleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all available API actions
	// (GET /actions)
	GetActions(ctx echo.Context) error
	// Request reset password code
	// (POST /auth/forgot-password)
	ForgotPassword(ctx echo.Context) error
	// Login and get access token
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Logout current access token
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// Get current user from access token
	// (GET /auth/me)
	GetMe(ctx echo.Context) error
	// Register new user
	// (POST /auth/register)
	Register(ctx echo.Context) error
	// Resend email verification code
	// (POST /auth/resend-verification)
	ResendVerification(ctx echo.Context) error
	// Reset password with emailed code
	// (POST /auth/reset-password)
	ResetPassword(ctx echo.Context) error
	// Verify registered user email
	// (POST /auth/verify-email)
	VerifyEmail(ctx echo.Context) error
	// Check application liveness
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Check application readiness
	// (GET /readiness)
	GetReadiness(ctx echo.Context) error
	// Create role and optional access mapping
	// (POST /roles)
	CreateRole(ctx echo.Context) error
	// Update role and optional access mapping
	// (PUT /roles/{role_id})
	UpdateRole(ctx echo.Context, roleId int64) error
	// Replace action mapping for a role
	// (PUT /roles/{role_id}/actions)
	SetRoleActions(ctx echo.Context, roleId int64) error
	// Get all test table rows
	// (GET /test_db)
	GetTestDBList(ctx echo.Context, params GetTestDBListParams) error
	// Create test table row
	// (POST /test_db)
	CreateTestDB(ctx echo.Context) error
	// Delete test table row
	// (DELETE /test_db/{test_id})
	DeleteTestDB(ctx echo.Context, testId openapi_types.UUID) error
	// Get test table row by id
	// (GET /test_db/{test_id})
	GetTestDBByID(ctx echo.Context, testId openapi_types.UUID) error
	// Update test table row
	// (PUT /test_db/{test_id})
	UpdateTestDB(ctx echo.Context, testId openapi_types.UUID) error
	// Assign a role to a user
	// (PUT /users/{user_id}/role)
	AssignUserRole(ctx echo.Context, userId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetActions converts echo context to params.
func (w *ServerInterfaceWrapper) GetActions(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetActions(ctx)
	return err
}

// ForgotPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ForgotPassword(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ForgotPassword(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// Register converts echo context to params.
func (w *ServerInterfaceWrapper) Register(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Register(ctx)
	return err
}

// ResendVerification converts echo context to params.
func (w *ServerInterfaceWrapper) ResendVerification(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendVerification(ctx)
	return err
}

// ResetPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ResetPassword(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResetPassword(ctx)
	return err
}

// VerifyEmail converts echo context to params.
func (w *ServerInterfaceWrapper) VerifyEmail(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.VerifyEmail(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetReadiness converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReadiness(ctx)
	return err
}

// CreateRole converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRole(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRole(ctx)
	return err
}

// UpdateRole converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateRole(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "role_id" -------------
	var roleId int64

	err = runtime.BindStyledParameterWithOptions("simple", "role_id", ctx.Param("role_id"), &roleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter role_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateRole(ctx, roleId)
	return err
}

// SetRoleActions converts echo context to params.
func (w *ServerInterfaceWrapper) SetRoleActions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "role_id" -------------
	var roleId int64

	err = runtime.BindStyledParameterWithOptions("simple", "role_id", ctx.Param("role_id"), &roleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter role_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetRoleActions(ctx, roleId)
	return err
}

// GetTestDBList converts echo context to params.
func (w *ServerInterfaceWrapper) GetTestDBList(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTestDBListParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "order_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order_by", ctx.QueryParams(), &params.OrderBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order_by: %s", err))
	}

	// ------------- Optional query parameter "order_dir" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order_dir", ctx.QueryParams(), &params.OrderDir, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order_dir: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTestDBList(ctx, params)
	return err
}

// CreateTestDB converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTestDB(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTestDB(ctx)
	return err
}

// DeleteTestDB converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTestDB(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "test_id" -------------
	var testId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "test_id", ctx.Param("test_id"), &testId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter test_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTestDB(ctx, testId)
	return err
}

// GetTestDBByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetTestDBByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "test_id" -------------
	var testId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "test_id", ctx.Param("test_id"), &testId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter test_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTestDBByID(ctx, testId)
	return err
}

// UpdateTestDB converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTestDB(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "test_id" -------------
	var testId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "test_id", ctx.Param("test_id"), &testId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter test_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTestDB(ctx, testId)
	return err
}

// AssignUserRole converts echo context to params.
func (w *ServerInterfaceWrapper) AssignUserRole(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AssignUserRole(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/actions", wrapper.GetActions, options.OperationMiddlewares["GetActions"]...)
	router.POST(options.BaseURL+"/auth/forgot-password", wrapper.ForgotPassword, options.OperationMiddlewares["ForgotPassword"]...)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login, options.OperationMiddlewares["Login"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout, options.OperationMiddlewares["Logout"]...)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetMe, options.OperationMiddlewares["GetMe"]...)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register, options.OperationMiddlewares["Register"]...)
	router.POST(options.BaseURL+"/auth/resend-verification", wrapper.ResendVerification, options.OperationMiddlewares["ResendVerification"]...)
	router.POST(options.BaseURL+"/auth/reset-password", wrapper.ResetPassword, options.OperationMiddlewares["ResetPassword"]...)
	router.POST(options.BaseURL+"/auth/verify-email", wrapper.VerifyEmail, options.OperationMiddlewares["VerifyEmail"]...)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth, options.OperationMiddlewares["GetHealth"]...)
	router.GET(options.BaseURL+"/readiness", wrapper.GetReadiness, options.OperationMiddlewares["GetReadiness"]...)
	router.POST(options.BaseURL+"/roles", wrapper.CreateRole, options.OperationMiddlewares["CreateRole"]...)
	router.PUT(options.BaseURL+"/roles/:role_id", wrapper.UpdateRole, options.OperationMiddlewares["UpdateRole"]...)
	router.PUT(options.BaseURL+"/roles/:role_id/actions", wrapper.SetRoleActions, options.OperationMiddlewares["SetRoleActions"]...)
	router.GET(options.BaseURL+"/test_db", wrapper.GetTestDBList, options.OperationMiddlewares["GetTestDBList"]...)
	router.POST(options.BaseURL+"/test_db", wrapper.CreateTestDB, options.OperationMiddlewares["CreateTestDB"]...)
	router.DELETE(options.BaseURL+"/test_db/:test_id", wrapper.DeleteTestDB, options.OperationMiddlewares["DeleteTestDB"]...)
	router.GET(options.BaseURL+"/test_db/:test_id", wrapper.GetTestDBByID, options.OperationMiddlewares["GetTestDBByID"]...)
	router.PUT(options.BaseURL+"/test_db/:test_id", wrapper.UpdateTestDB, options.OperationMiddlewares["UpdateTestDB"]...)
	router.PUT(options.BaseURL+"/users/:user_id/role", wrapper.AssignUserRole, options.OperationMiddlewares["AssignUserRole"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3FxbcxO5Ev4rqjnncRI7hKV283RyA7IFZ7MOHB4g5ZJH7bE2M9IgaWK8lP/7KV3mrrGdENth3wiW1K3u",
	"r1t9s78HEU8zzoApGZx8D2Q0gxSbf55GinL2jkp1en01AplxJkF/kAmegVAUzLKIE/O/8A2nWQLBSXDz",
	"8fz88uYmCAO1yPR/SCUoi4NlGBCssF5MFaRm978FTIOT4F+Dio2B42FgGSgpL8vzsBB4of9OQUoct8jL",
	"PIpAyi75ZRgI+JpTASQ4+WwZr85wzN2W2/jkL4iUJtNipCMCbD4fE5BRk5U3oJACqdDFGUqoVD6RuM2U",
	"NLYehcGUixSr4CSgTL16WW2lTEEMorbXftAgfPnBRwsYyThlqrl4oFkck8laiVWsho07NxmpkfEKU0oa",
	"s48SxIgnMIKvOUjVlangCTxGKC2Wi2O8nORqdi6AAFMUJ72cZFjKORekhTKIBKijF8dBjalyaRiklL0D",
	"FqtZcPKrRxO5BMFw2lKboH/f0bVqKPeGFcG++2k5P735rrRaR7Vut7uy0zbpzm0hxTTxyPw/7u/DiKd1",
	"hdr1HklM8yQZdxU40oeh02iWYuLbpuHY3KGVGfQAxOG/5CbPKQm2ACZr0TVYGTZ9Ej4XgBWsNNzSScgG",
	"O5+Pwhe3YeX4N/BubW9vbLnrZDFJKVt7z2qz716XaaYWT2cnXrwTSEABeSjevewKwcVDeL0cjcZnpxfj",
	"0eWfHy9vPmzMM2X3OKEECattNOFk8RQXeM1FzNW18169WHoic23xZ1f52HoLOFGz3fpLS3MP3rJFuCt8",
	"dt9kIeER9jpDCeKeRi2GZzyFORd33g0Kq7zpHwJ+t/ZubltFMDRM+i73jseU7VaRhuQe9Nik6/HHmt5Y",
	"8Ttg+u9uUPgtowLkmLIGp8evhkOvV9YHeULOM8DC95R1YsgaO43TGpz4LnqNY8qwfl3eg1VH86YJTWkz",
	"tD3y3oALAmI8WTT5N0Gw/321GwgVrYfHhL6d1Vlb50d+MSrcdG0vftko5jcbx5pI04CO18bCmQWSFVPB",
	"QfPAmnDq1/ZpYwSYUAZS7tbKSrJ7sLSS9vkMorvuZf3PPlZ4giWgiLMpjXNhEIyoRJkACUxt6iAF4A0e",
	"X7dzJfsr1KUvZt0GIVQzipPrxoqNdGPls/Tw8MMXCwse/TeMqVQ6AdhuQPHo+P/Z5ZLVPRoJQHHvlfnl",
	"SMOX/A8EndII2xLJMwnkNGvrw8uuc3r564uj37QaUvytEPmrhgJe+coqT4UqBvOxHyIM5jc/ghKv5MLC",
	"9zXoeuXJE9ixnzc55u5dfJ3smtz2R3JZe5J8wloolWN96H1TRErkUK6dcJ4AZg/PpcOnLsfVGaiz7lPJ",
	"DSgDPyuxndcd+mqg/hfoA0h1cbZbU7E092AslvA7KtU+2gPda/9Ye0CvXy/sVhKymfDc0f0y7EW1tpCx",
	"ch+xPEnwpGPWNT32Ht+rHlPQI2OsGsZBsIIDRU0s0BFTscdmUO3q5BomwwddKSzTsvV10JYmqnyudkef",
	"Bj5mZH81zSfx2ppVrLg/+e7c1wRsi0sdAfwskdGq6KWrUlORinJB1eJGW6290sTUJ05zzWrx1+uC7u+f",
	"PgShbX4akbdqGTOlsmC5NMUSpYPk5IJHpX0Kmml4BCfBGY7ugBH0hqq3+QSNIOOSKi50dpOLxJ0kTwaD",
	"mKpZPtHXHxiBYDEcDsqSmQYGm/IugbduBTq9vtIpJEZvOJo4qvIOElCcoUxwLQk0yWmi0JQLlAmNsoiy",
	"GGGkDziQapFAuRWLaEYVRCoXcPiFXSlEWZTkBCS6jGYcCZ4ryuIQXXOpYgE3f75DtpKD1EzwPJ6hN3+M",
	"3ofo908fEM7VDJhyOUGINGoH1oSQzoRJsTXiTAmehOhmjuMYxOCPDNjp9VWIjIbRfS21CJHOlhUqwlQ0",
	"Tfg8RCMgVB6YDBKllJAE5lhAiFIa20Rbhggzgi54dAcCyTzLuFCHX9gXVijr9PrqBBV6mcCh0YdUWCgQ",
	"WkFf2GvBmdJLP8FEUgXV8u7aJgSqlSsVXiPxoH0HU/hiwjWqjG3V4RGEwT0IaXFzdDg8HJpSVgYMZzQ4",
	"CY4Ph4fHJsVTMwPlQS0mjcE4BetYKGdXxHazXRCm4zf3pJjlL4ZD6zX0HcxOnGWJ09zgL8lZNVuwWaTb",
	"Hjswxte0BbvQ9tXrNh+cfG5a++fb5W0YyDxNsVi4rjxOEoTvMTWPj7EmXF5N4VhWpcrgVh8+0KAeTE3b",
	"4qCeomVcekTV7G8E1n2BVGecLJ5MUv4myrLpLfVTstyiujqdM4+mRk3L1W4bSWAK0SlSM3DWTiUSrn4D",
	"RGP15VOy2eiYeXi8ana6LKJKyDjhtn2Qi/ZKwGi41eCS8NgW1f0gMYX7LWHDP9uwY2x0mjAeuZs1qAjK",
	"jdaPdq/1ovSF9FtZWG0TApZR/ZbE2n+4x69oY/QjgOdqJQT053u2T8vF3pTwkWlZcUH/BvIwT+4Yj3Ih",
	"tDvZUCm2Utr3xL2Hrb5unpkcj0jO3Y3MdMjPow/9skY11tFU8HRTtRTOv99aivL+lnxmu3uwkbc82jU0",
	"9JJn9VBq+r/tEJ01V20DB5zY+B++Ualk5+W2kkIM5qgYtupFoARGDuppxyowtrsfW4NlX5vlGYZ6dTZX",
	"BHoZMKKT0Yaon1vIp8XuyUTXRX0mRtwgR2j0qLaInZ8hQyhYtAH2vpGgXYsv0u8CpLZiTtXMogXWJgYG",
	"TouDsjrmB0itULcleHhKgc8QHJc1E9zjg6ffGzOgRDzuoAkNK9faK22jobK62YXFzAzjrYpL7bjeNmPT",
	"7vSjr+pSHW8KkAm9b9/eTH+gGh9IL2Ku6eLu7i5sby+KwZFVAiinS7YpA+9U03ox2BGWZRj8MjzeNy+M",
	"q4KfNWoRNYn69cIT9x0Ir4OqpsG35J+64+Y7jsnbcw++4hZPALkW0/MIYTbN1qx0TXne1DV4Zge+ioQt",
	"xVlGWdxXETXgGHx3Lf2lgUnuQUnVXzPVZoFTUCCkYY8yM8Ni/JodYaqPCDTUHNZktn7s4HY7gOz2Cnf8",
	"Xm4KyNww6gD5cneANMS1B5rynD2wemCF+1R4rLczvLhszpX8/Nj0z8k8U3w65ewXp1w4Ph6L2BFkCY6K",
	"2xQANR1XbHDch9XiG5crwp1quKYLzXbyFANieToBESLTjJS28HZ0GIQWxl9zME1oh2M3CV7JksAU54ky",
	"M10pZTTNU+/c+jJsE/+voYv4FAk+14m9QPr0PsrF8LmP9NAMFzjaw+FDOTnnSZ4yHWkTowHJhaIs7uOk",
	"NujuYaY2PgJMs1AfKKkmWHqGS6q5hTaTN1woRKgAg5jVvBEqepiz3zwoGLN/tb7bVrJwu0Vr9wyAeZN7",
	"MzIFREPE9Wv3FCcZOaPSmh7XNzbf6FamcawxX7Pxwqxvl+HKkNnKbUtBc3OibMcBc3f+0et851XE/IiI",
	"takAr/xrTnbw3Vnu0hpRAgq6irkw/18qZn0sULmDDWKBnom123035vkcFV9L3f0LPH/ss2t1tQkMwjXP",
	"69ni6uIfoe2N7Y6AwjT5mbRd/ohGqWo0WSArYZ/f7c9B92Hdz8K/7wFn+wvs5z+Yf274uuQShBx8d7+f",
	"sBwUP+3gxV/zR082QmD1wwzPDoH+n3B5hp0D2ys3+aZheQ94NCxwx8UjgWnl7VJKpDjCnU52mVy6r+P3",
	"ZIqCkzxyvermQLJn8DXw5FhuuGPGTfJjjxgEy9vl/wMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
