// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetTestDBListParamsOrderBy.
const (
	DescTest GetTestDBListParamsOrderBy = "desc_test"
	TestId   GetTestDBListParamsOrderBy = "test_id"
)

// Valid indicates whether the value is a known member of the GetTestDBListParamsOrderBy enum.
func (e GetTestDBListParamsOrderBy) Valid() bool {
	switch e {
	case DescTest:
		return true
	case TestId:
		return true
	default:
		return false
	}
}

// Defines values for GetTestDBListParamsOrderDir.
const (
	Asc  GetTestDBListParamsOrderDir = "asc"
	Desc GetTestDBListParamsOrderDir = "desc"
)

// Valid indicates whether the value is a known member of the GetTestDBListParamsOrderDir enum.
func (e GetTestDBListParamsOrderDir) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// AuthCredentialRequest defines model for AuthCredentialRequest.
type AuthCredentialRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AuthUserAPIResponse defines model for AuthUserAPIResponse.
type AuthUserAPIResponse struct {
	Code    string           `json:"code"`
	Data    AuthUserResponse `json:"data"`
	Message string           `json:"message"`
}

// AuthUserResponse defines model for AuthUserResponse.
type AuthUserResponse struct {
	Role     string             `json:"role"`
	UserId   openapi_types.UUID `json:"user_id"`
	Username string             `json:"username"`
}

// EmptyAPIResponse defines model for EmptyAPIResponse.
type EmptyAPIResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// HealthAPIResponse defines model for HealthAPIResponse.
type HealthAPIResponse struct {
	Code    string         `json:"code"`
	Data    HealthResponse `json:"data"`
	Message string         `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Env     string `json:"env"`
	Service string `json:"service"`
	Status  string `json:"status"`
}

// LoginAPIResponse defines model for LoginAPIResponse.
type LoginAPIResponse struct {
	Code    string        `json:"code"`
	Data    LoginResponse `json:"data"`
	Message string        `json:"message"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Limit      int    `json:"limit"`
	OrderBy    string `json:"order_by"`
	OrderDir   string `json:"order_dir"`
	Page       int    `json:"page"`
	Total      int64  `json:"total"`
	TotalPages int    `json:"total_pages"`
}

// ReadinessAPIResponse defines model for ReadinessAPIResponse.
type ReadinessAPIResponse struct {
	Code    string            `json:"code"`
	Data    ReadinessResponse `json:"data"`
	Message string            `json:"message"`
}

// ReadinessCheck defines model for ReadinessCheck.
type ReadinessCheck struct {
	Message *string `json:"message,omitempty"`
	Status  string  `json:"status"`
}

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Checks map[string]ReadinessCheck `json:"checks"`
	Status string                    `json:"status"`
}

// TestDBAPIResponse defines model for TestDBAPIResponse.
type TestDBAPIResponse struct {
	Code    string         `json:"code"`
	Data    TestDBResponse `json:"data"`
	Message string         `json:"message"`
}

// TestDBListResponse defines model for TestDBListResponse.
type TestDBListResponse struct {
	Code    string           `json:"code"`
	Data    []TestDBResponse `json:"data"`
	Message string           `json:"message"`
	Meta    PaginationMeta   `json:"meta"`
}

// TestDBRequest defines model for TestDBRequest.
type TestDBRequest struct {
	DescTest *string `json:"desc_test,omitempty"`
}

// TestDBResponse defines model for TestDBResponse.
type TestDBResponse struct {
	DescTest *string            `json:"desc_test,omitempty"`
	TestId   openapi_types.UUID `json:"test_id"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetTestDBListParams defines parameters for GetTestDBList.
type GetTestDBListParams struct {
	// Page Page number, starts from 1.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of rows per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// OrderBy Column used for sorting.
	OrderBy *GetTestDBListParamsOrderBy `form:"order_by,omitempty" json:"order_by,omitempty"`

	// OrderDir Sort direction.
	OrderDir *GetTestDBListParamsOrderDir `form:"order_dir,omitempty" json:"order_dir,omitempty"`
}

// GetTestDBListParamsOrderBy defines parameters for GetTestDBList.
type GetTestDBListParamsOrderBy string

// GetTestDBListParamsOrderDir defines parameters for GetTestDBList.
type GetTestDBListParamsOrderDir string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = AuthCredentialRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = AuthCredentialRequest

// CreateTestDBJSONRequestBody defines body for CreateTestDB for application/json ContentType.
type CreateTestDBJSONRequestBody = TestDBRequest

// UpdateTestDBJSONRequestBody defines body for UpdateTestDB for application/json ContentType.
type UpdateTestDBJSONRequestBody = TestDBRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login and get access token
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Get current user from access token
	// (GET /auth/me)
	GetMe(ctx echo.Context) error
	// Register new user
	// (POST /auth/register)
	Register(ctx echo.Context) error
	// Check application liveness
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Check application readiness
	// (GET /readiness)
	GetReadiness(ctx echo.Context) error
	// Get all test table rows
	// (GET /test_db)
	GetTestDBList(ctx echo.Context, params GetTestDBListParams) error
	// Create test table row
	// (POST /test_db)
	CreateTestDB(ctx echo.Context) error
	// Delete test table row
	// (DELETE /test_db/{test_id})
	DeleteTestDB(ctx echo.Context, testId openapi_types.UUID) error
	// Get test table row by id
	// (GET /test_db/{test_id})
	GetTestDBByID(ctx echo.Context, testId openapi_types.UUID) error
	// Update test table row
	// (PUT /test_db/{test_id})
	UpdateTestDB(ctx echo.Context, testId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// Register converts echo context to params.
func (w *ServerInterfaceWrapper) Register(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Register(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetReadiness converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReadiness(ctx)
	return err
}

// GetTestDBList converts echo context to params.
func (w *ServerInterfaceWrapper) GetTestDBList(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTestDBListParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "order_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order_by", ctx.QueryParams(), &params.OrderBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order_by: %s", err))
	}

	// ------------- Optional query parameter "order_dir" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order_dir", ctx.QueryParams(), &params.OrderDir, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order_dir: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTestDBList(ctx, params)
	return err
}

// CreateTestDB converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTestDB(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTestDB(ctx)
	return err
}

// DeleteTestDB converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTestDB(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "test_id" -------------
	var testId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "test_id", ctx.Param("test_id"), &testId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter test_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTestDB(ctx, testId)
	return err
}

// GetTestDBByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetTestDBByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "test_id" -------------
	var testId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "test_id", ctx.Param("test_id"), &testId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter test_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTestDBByID(ctx, testId)
	return err
}

// UpdateTestDB converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTestDB(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "test_id" -------------
	var testId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "test_id", ctx.Param("test_id"), &testId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter test_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTestDB(ctx, testId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login, options.OperationMiddlewares["Login"]...)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetMe, options.OperationMiddlewares["GetMe"]...)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register, options.OperationMiddlewares["Register"]...)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth, options.OperationMiddlewares["GetHealth"]...)
	router.GET(options.BaseURL+"/readiness", wrapper.GetReadiness, options.OperationMiddlewares["GetReadiness"]...)
	router.GET(options.BaseURL+"/test_db", wrapper.GetTestDBList, options.OperationMiddlewares["GetTestDBList"]...)
	router.POST(options.BaseURL+"/test_db", wrapper.CreateTestDB, options.OperationMiddlewares["CreateTestDB"]...)
	router.DELETE(options.BaseURL+"/test_db/:test_id", wrapper.DeleteTestDB, options.OperationMiddlewares["DeleteTestDB"]...)
	router.GET(options.BaseURL+"/test_db/:test_id", wrapper.GetTestDBByID, options.OperationMiddlewares["GetTestDBByID"]...)
	router.PUT(options.BaseURL+"/test_db/:test_id", wrapper.UpdateTestDB, options.OperationMiddlewares["UpdateTestDB"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fldcxq5Ev0rKt37OGVwnKTu5c1fm3gr2fLiuPbBRVFipgHFM9Kk1WObpPjvW5JmgJkRBmptSPbNYEl9",
	"+pzuVrf4wWOd5VqBIsN7P7iJp5AJ9+dpQdNzhAQUSZH24VsBhuw/ctQ5IElwy3JhzKPGxP4NTyLLU+A9",
	"biBGoOM3JzziY42ZIN5bLo14JtUnUBOa8t7/Ik6z3G0ilGrC5xEvDKASGdQPRfn9XvLW8nnEEb4VEiHh",
	"vbvl3mhpcLDYpEdfISZrw/p3awBPr6/6YHKtDLS9i3XSAHFze35+eXPDA6gTQcIu/i/CmPf4fzpLbjsl",
	"sZ3K6sLkPOIZGCMmDTumiGMwZqO7DuHyjBLFcw6v9xZ12kBhyeRrBBpKJ/pC3qKQCX8FMYfu2BVZHcyQ",
	"h5dZTrOX0zOoSwIpECS76hKEi6hxF6yX/f7w7PRi2L/88/by5svWmKV6EKlMGPokZiOdzF7CgY8gUpru",
	"N4G8zQOkT8Nwy1NQD3UIqY5FGnLTAD7IuAF4qjN41Hgf3ECCClNfr+83+lZuWxqMHMiQc5/0RKr9CulM",
	"HkDHut2Wn8LZG5K+B2U/t3yDp1wimKFUNaQn77vdhTWpCCaAdrk7aOi/X3XsDASGamvDrxqc2mk1JCFH",
	"r8VEKkFSq8/g5ah7mspMUg3UcdADjQngcDSr4ycwNAwXfL8hkVjfIUwcWp03NT8O00girS17826ltZCK",
	"3r/lazcOrZF6Ap20Fzeoz30geZoqBPUDV8hZdTukRh9EIhUYs98sW5g9QKYtbJ9PIb5vOxu+XwWJkTDA",
	"Yq3GclKgi2AmDcsRDCjatkAiiC1uuXLns/Cfkcs65stGkkgLVKTXtRVbaeP5mQcw/GPHogpjyMMvYOji",
	"bL8B6W0eIBq94U/S0At7Kwkys7vb5XkCUcx2p8Gu30x24wrYjrzy6PUcrp0FEzDxkMp/qSJNxch6QVhA",
	"SMe1x6+TZ5fzo8UNtXlGadBSbWwz4Jq3uEBJsxtLsYc1cle5Ha+Wn36rLP7+l+3TnSD2pFHj2p8S5Xxu",
	"D5ZqrF3DIclJ/7FsCNnp9RWP+AOgkVrxHj8+6h513T2bgxK55D1+ctQ9OnEDL00dpI4oaNpJbavjaNSe",
	"M0umC4erhPd8J8S972DozE4FLgkU2Tprq1qepzJ2OzpfjVbLJ4Jt5tz268G8TrUVzn3hBXfI33S7Lwai",
	"1dU6+zaKUObk2XRrWJVn84i/7R6/GID6hBewflVOZtV0yzSyxauFC7ciywTOFkCFStgEiPm+kC36QjEx",
	"rl20QTiwG30E+Kl7AgH1PwB9dtP0a7EfemAJUHBeIIIiR8He+b9VliaN8jsktfTmvbt6Yt8N5oNVOT4A",
	"sXgFOhujzraVBWEiDQGuz81+teKnS8/jfQeIXcIqxqxMNka6+89RrFiy9v+/xxitaoNIXevH4EkaMo3y",
	"UAUMU/DIqme7dvhN3SvGc0XBv3O8ZmFoPxsFvD5dHm+bf5HKB2i47NpmtoKD2UWq7JdK30uHvfdYddzP",
	"EbBoy1+Tg+A4uJkG3/vPI/6ue3JoLEpThWeDLLjCaFAX13Elo+dUWbbvrs9BkQEBGlen6zCvxQSYKrIR",
	"YMQMCSTji/PxEbdtFu/xbwWgHaH8s3Q16S/ZSmAsipTcW0QmlcyKLPguMY+axv9wdpkeM9SPhuVg7/MJ",
	"rLNcPS6ETHcjnomn0na3uyuSc50WmbKlIGFjjcxoJKkm65CsPGQEwKw894CyEO5Wvlm25YNAa93EdaOR",
	"WCIRYvvF83ASiWvw+MekCov/ZO2EIAxeMY8DU2Ugc8o5DBIbFSyV1S1ygFvM8cwWCbR70yPSlFmxGdnp",
	"y4X5SlpXmTyYR2s6m3MEQeB5e6Xupj6m7rmraT+qBNTo60cWOyJ2bDs9ew0Bgvyv1NXOjzJZ5z6JUiBo",
	"C3Phvl8I06ixLkntfLnM0WUFqLO7mrGbJu/XzM3Wz4FrhKh+0nMp+XZ/KWlt20t0rAu1Yxh4rbYJg2jD",
	"jXo2u7r4V6i9dd4lQEKmv5LatuzWpWajGfMMh+puERD8Nk/EYbL7p6jvB4izwjH+S5UVHyRb3S7l79hV",
	"ABWY8h7v8Plg/ncAAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
