// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package http

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for GetTestDBListParamsOrderBy.
const (
	DescTest GetTestDBListParamsOrderBy = "desc_test"
	TestId   GetTestDBListParamsOrderBy = "test_id"
)

// Valid indicates whether the value is a known member of the GetTestDBListParamsOrderBy enum.
func (e GetTestDBListParamsOrderBy) Valid() bool {
	switch e {
	case DescTest:
		return true
	case TestId:
		return true
	default:
		return false
	}
}

// Defines values for GetTestDBListParamsOrderDir.
const (
	Asc  GetTestDBListParamsOrderDir = "asc"
	Desc GetTestDBListParamsOrderDir = "desc"
)

// Valid indicates whether the value is a known member of the GetTestDBListParamsOrderDir enum.
func (e GetTestDBListParamsOrderDir) Valid() bool {
	switch e {
	case Asc:
		return true
	case Desc:
		return true
	default:
		return false
	}
}

// ActionListAPIResponse defines model for ActionListAPIResponse.
type ActionListAPIResponse struct {
	Code    string           `json:"code"`
	Data    []ActionResponse `json:"data"`
	Message string           `json:"message"`
}

// ActionResponse defines model for ActionResponse.
type ActionResponse struct {
	ActionDesc string `json:"action_desc"`
	ActionId   int64  `json:"action_id"`
	ActionType string `json:"action_type"`
	Endpoint   string `json:"endpoint"`
}

// AssignUserRoleRequest defines model for AssignUserRoleRequest.
type AssignUserRoleRequest struct {
	RoleId int64 `json:"role_id"`
}

// AuthCredentialRequest defines model for AuthCredentialRequest.
type AuthCredentialRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// AuthUserAPIResponse defines model for AuthUserAPIResponse.
type AuthUserAPIResponse struct {
	Code    string           `json:"code"`
	Data    AuthUserResponse `json:"data"`
	Message string           `json:"message"`
}

// AuthUserResponse defines model for AuthUserResponse.
type AuthUserResponse struct {
	Email    *openapi_types.Email `json:"email,omitempty"`
	FullName *string              `json:"full_name,omitempty"`
	Role     string               `json:"role"`
	UserId   openapi_types.UUID   `json:"user_id"`
	Username string               `json:"username"`
}

// CreateRoleRequest defines model for CreateRoleRequest.
type CreateRoleRequest struct {
	ActionIds *[]int64 `json:"action_ids,omitempty"`
	RoleDesc  string   `json:"role_desc"`
}

// EmptyAPIResponse defines model for EmptyAPIResponse.
type EmptyAPIResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ForgotPasswordRequest defines model for ForgotPasswordRequest.
type ForgotPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// HealthAPIResponse defines model for HealthAPIResponse.
type HealthAPIResponse struct {
	Code    string         `json:"code"`
	Data    HealthResponse `json:"data"`
	Message string         `json:"message"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Env     string `json:"env"`
	Service string `json:"service"`
	Status  string `json:"status"`
}

// LoginAPIResponse defines model for LoginAPIResponse.
type LoginAPIResponse struct {
	Code    string        `json:"code"`
	Data    LoginResponse `json:"data"`
	Message string        `json:"message"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
	TokenType   string `json:"token_type"`
}

// PaginationMeta defines model for PaginationMeta.
type PaginationMeta struct {
	Limit      int    `json:"limit"`
	OrderBy    string `json:"order_by"`
	OrderDir   string `json:"order_dir"`
	Page       int    `json:"page"`
	Total      int64  `json:"total"`
	TotalPages int    `json:"total_pages"`
}

// ReadinessAPIResponse defines model for ReadinessAPIResponse.
type ReadinessAPIResponse struct {
	Code    string            `json:"code"`
	Data    ReadinessResponse `json:"data"`
	Message string            `json:"message"`
}

// ReadinessCheck defines model for ReadinessCheck.
type ReadinessCheck struct {
	Message *string `json:"message,omitempty"`
	Status  string  `json:"status"`
}

// ReadinessResponse defines model for ReadinessResponse.
type ReadinessResponse struct {
	Checks map[string]ReadinessCheck `json:"checks"`
	Status string                    `json:"status"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	FullName string              `json:"full_name"`
	Password string              `json:"password"`
	Username string              `json:"username"`
}

// ResendVerificationRequest defines model for ResendVerificationRequest.
type ResendVerificationRequest struct {
	Email openapi_types.Email `json:"email"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Code        string              `json:"code"`
	Email       openapi_types.Email `json:"email"`
	NewPassword string              `json:"new_password"`
}

// RoleAPIResponse defines model for RoleAPIResponse.
type RoleAPIResponse struct {
	Code    string       `json:"code"`
	Data    RoleResponse `json:"data"`
	Message string       `json:"message"`
}

// RoleResponse defines model for RoleResponse.
type RoleResponse struct {
	ActionIds *[]int64          `json:"action_ids,omitempty"`
	Actions   *[]ActionResponse `json:"actions,omitempty"`
	IsActive  bool              `json:"is_active"`
	RoleDesc  string            `json:"role_desc"`
	RoleId    int64             `json:"role_id"`
}

// SetRoleActionsRequest defines model for SetRoleActionsRequest.
type SetRoleActionsRequest struct {
	ActionIds []int64 `json:"action_ids"`
}

// TestDBAPIResponse defines model for TestDBAPIResponse.
type TestDBAPIResponse struct {
	Code    string         `json:"code"`
	Data    TestDBResponse `json:"data"`
	Message string         `json:"message"`
}

// TestDBListResponse defines model for TestDBListResponse.
type TestDBListResponse struct {
	Code    string           `json:"code"`
	Data    []TestDBResponse `json:"data"`
	Message string           `json:"message"`
	Meta    PaginationMeta   `json:"meta"`
}

// TestDBRequest defines model for TestDBRequest.
type TestDBRequest struct {
	DescTest *string `json:"desc_test,omitempty"`
}

// TestDBResponse defines model for TestDBResponse.
type TestDBResponse struct {
	DescTest *string            `json:"desc_test,omitempty"`
	TestId   openapi_types.UUID `json:"test_id"`
}

// UpdateRoleRequest defines model for UpdateRoleRequest.
type UpdateRoleRequest struct {
	ActionIds *[]int64 `json:"action_ids,omitempty"`
	IsActive  *bool    `json:"is_active,omitempty"`
	RoleDesc  *string  `json:"role_desc,omitempty"`
}

// VerifyEmailRequest defines model for VerifyEmailRequest.
type VerifyEmailRequest struct {
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
}

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetTestDBListParams defines parameters for GetTestDBList.
type GetTestDBListParams struct {
	// Page Page number, starts from 1.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of rows per page.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// OrderBy Column used for sorting.
	OrderBy *GetTestDBListParamsOrderBy `form:"order_by,omitempty" json:"order_by,omitempty"`

	// OrderDir Sort direction.
	OrderDir *GetTestDBListParamsOrderDir `form:"order_dir,omitempty" json:"order_dir,omitempty"`
}

// GetTestDBListParamsOrderBy defines parameters for GetTestDBList.
type GetTestDBListParamsOrderBy string

// GetTestDBListParamsOrderDir defines parameters for GetTestDBList.
type GetTestDBListParamsOrderDir string

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody = ForgotPasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = AuthCredentialRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResendVerificationJSONRequestBody defines body for ResendVerification for application/json ContentType.
type ResendVerificationJSONRequestBody = ResendVerificationRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// VerifyEmailJSONRequestBody defines body for VerifyEmail for application/json ContentType.
type VerifyEmailJSONRequestBody = VerifyEmailRequest

// CreateRoleJSONRequestBody defines body for CreateRole for application/json ContentType.
type CreateRoleJSONRequestBody = CreateRoleRequest

// UpdateRoleJSONRequestBody defines body for UpdateRole for application/json ContentType.
type UpdateRoleJSONRequestBody = UpdateRoleRequest

// SetRoleActionsJSONRequestBody defines body for SetRoleActions for application/json ContentType.
type SetRoleActionsJSONRequestBody = SetRoleActionsRequest

// CreateTestDBJSONRequestBody defines body for CreateTestDB for application/json ContentType.
type CreateTestDBJSONRequestBody = TestDBRequest

// UpdateTestDBJSONRequestBody defines body for UpdateTestDB for application/json ContentType.
type UpdateTestDBJSONRequestBody = TestDBRequest

// AssignUserRoleJSONRequestBody defines body for AssignUserRole for application/json ContentType.
type AssignUserRoleJSONRequestBody = AssignUserRoleRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all available API actions
	// (GET /actions)
	GetActions(ctx echo.Context) error
	// Request reset password code
	// (POST /auth/forgot-password)
	ForgotPassword(ctx echo.Context) error
	// Login and get access token
	// (POST /auth/login)
	Login(ctx echo.Context) error
	// Logout current access token
	// (POST /auth/logout)
	Logout(ctx echo.Context) error
	// Get current user from access token
	// (GET /auth/me)
	GetMe(ctx echo.Context) error
	// Register new user
	// (POST /auth/register)
	Register(ctx echo.Context) error
	// Resend email verification code
	// (POST /auth/resend-verification)
	ResendVerification(ctx echo.Context) error
	// Reset password with emailed code
	// (POST /auth/reset-password)
	ResetPassword(ctx echo.Context) error
	// Verify registered user email
	// (POST /auth/verify-email)
	VerifyEmail(ctx echo.Context) error
	// Check application liveness
	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Check application readiness
	// (GET /readiness)
	GetReadiness(ctx echo.Context) error
	// Create role and optional access mapping
	// (POST /roles)
	CreateRole(ctx echo.Context) error
	// Update role and optional access mapping
	// (PUT /roles/{role_id})
	UpdateRole(ctx echo.Context, roleId int64) error
	// Replace action mapping for a role
	// (PUT /roles/{role_id}/actions)
	SetRoleActions(ctx echo.Context, roleId int64) error
	// Get all test table rows
	// (GET /test_db)
	GetTestDBList(ctx echo.Context, params GetTestDBListParams) error
	// Create test table row
	// (POST /test_db)
	CreateTestDB(ctx echo.Context) error
	// Delete test table row
	// (DELETE /test_db/{test_id})
	DeleteTestDB(ctx echo.Context, testId openapi_types.UUID) error
	// Get test table row by id
	// (GET /test_db/{test_id})
	GetTestDBByID(ctx echo.Context, testId openapi_types.UUID) error
	// Update test table row
	// (PUT /test_db/{test_id})
	UpdateTestDB(ctx echo.Context, testId openapi_types.UUID) error
	// Assign a role to a user
	// (PUT /users/{user_id}/role)
	AssignUserRole(ctx echo.Context, userId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetActions converts echo context to params.
func (w *ServerInterfaceWrapper) GetActions(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetActions(ctx)
	return err
}

// ForgotPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ForgotPassword(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ForgotPassword(ctx)
	return err
}

// Login converts echo context to params.
func (w *ServerInterfaceWrapper) Login(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Login(ctx)
	return err
}

// Logout converts echo context to params.
func (w *ServerInterfaceWrapper) Logout(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Logout(ctx)
	return err
}

// GetMe converts echo context to params.
func (w *ServerInterfaceWrapper) GetMe(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMe(ctx)
	return err
}

// Register converts echo context to params.
func (w *ServerInterfaceWrapper) Register(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Register(ctx)
	return err
}

// ResendVerification converts echo context to params.
func (w *ServerInterfaceWrapper) ResendVerification(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResendVerification(ctx)
	return err
}

// ResetPassword converts echo context to params.
func (w *ServerInterfaceWrapper) ResetPassword(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ResetPassword(ctx)
	return err
}

// VerifyEmail converts echo context to params.
func (w *ServerInterfaceWrapper) VerifyEmail(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.VerifyEmail(ctx)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// GetReadiness converts echo context to params.
func (w *ServerInterfaceWrapper) GetReadiness(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReadiness(ctx)
	return err
}

// CreateRole converts echo context to params.
func (w *ServerInterfaceWrapper) CreateRole(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateRole(ctx)
	return err
}

// UpdateRole converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateRole(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "role_id" -------------
	var roleId int64

	err = runtime.BindStyledParameterWithOptions("simple", "role_id", ctx.Param("role_id"), &roleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter role_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateRole(ctx, roleId)
	return err
}

// SetRoleActions converts echo context to params.
func (w *ServerInterfaceWrapper) SetRoleActions(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "role_id" -------------
	var roleId int64

	err = runtime.BindStyledParameterWithOptions("simple", "role_id", ctx.Param("role_id"), &roleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter role_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetRoleActions(ctx, roleId)
	return err
}

// GetTestDBList converts echo context to params.
func (w *ServerInterfaceWrapper) GetTestDBList(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTestDBListParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", ctx.QueryParams(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "order_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order_by", ctx.QueryParams(), &params.OrderBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order_by: %s", err))
	}

	// ------------- Optional query parameter "order_dir" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "order_dir", ctx.QueryParams(), &params.OrderDir, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order_dir: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTestDBList(ctx, params)
	return err
}

// CreateTestDB converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTestDB(ctx echo.Context) error {
	var err error

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTestDB(ctx)
	return err
}

// DeleteTestDB converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteTestDB(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "test_id" -------------
	var testId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "test_id", ctx.Param("test_id"), &testId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter test_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteTestDB(ctx, testId)
	return err
}

// GetTestDBByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetTestDBByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "test_id" -------------
	var testId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "test_id", ctx.Param("test_id"), &testId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter test_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTestDBByID(ctx, testId)
	return err
}

// UpdateTestDB converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateTestDB(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "test_id" -------------
	var testId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "test_id", ctx.Param("test_id"), &testId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter test_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateTestDB(ctx, testId)
	return err
}

// AssignUserRole converts echo context to params.
func (w *ServerInterfaceWrapper) AssignUserRole(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "user_id" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", ctx.Param("user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	ctx.Set(string(BearerAuthScopes), []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AssignUserRole(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/actions", wrapper.GetActions, options.OperationMiddlewares["GetActions"]...)
	router.POST(options.BaseURL+"/auth/forgot-password", wrapper.ForgotPassword, options.OperationMiddlewares["ForgotPassword"]...)
	router.POST(options.BaseURL+"/auth/login", wrapper.Login, options.OperationMiddlewares["Login"]...)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout, options.OperationMiddlewares["Logout"]...)
	router.GET(options.BaseURL+"/auth/me", wrapper.GetMe, options.OperationMiddlewares["GetMe"]...)
	router.POST(options.BaseURL+"/auth/register", wrapper.Register, options.OperationMiddlewares["Register"]...)
	router.POST(options.BaseURL+"/auth/resend-verification", wrapper.ResendVerification, options.OperationMiddlewares["ResendVerification"]...)
	router.POST(options.BaseURL+"/auth/reset-password", wrapper.ResetPassword, options.OperationMiddlewares["ResetPassword"]...)
	router.POST(options.BaseURL+"/auth/verify-email", wrapper.VerifyEmail, options.OperationMiddlewares["VerifyEmail"]...)
	router.GET(options.BaseURL+"/health", wrapper.GetHealth, options.OperationMiddlewares["GetHealth"]...)
	router.GET(options.BaseURL+"/readiness", wrapper.GetReadiness, options.OperationMiddlewares["GetReadiness"]...)
	router.POST(options.BaseURL+"/roles", wrapper.CreateRole, options.OperationMiddlewares["CreateRole"]...)
	router.PUT(options.BaseURL+"/roles/:role_id", wrapper.UpdateRole, options.OperationMiddlewares["UpdateRole"]...)
	router.PUT(options.BaseURL+"/roles/:role_id/actions", wrapper.SetRoleActions, options.OperationMiddlewares["SetRoleActions"]...)
	router.GET(options.BaseURL+"/test_db", wrapper.GetTestDBList, options.OperationMiddlewares["GetTestDBList"]...)
	router.POST(options.BaseURL+"/test_db", wrapper.CreateTestDB, options.OperationMiddlewares["CreateTestDB"]...)
	router.DELETE(options.BaseURL+"/test_db/:test_id", wrapper.DeleteTestDB, options.OperationMiddlewares["DeleteTestDB"]...)
	router.GET(options.BaseURL+"/test_db/:test_id", wrapper.GetTestDBByID, options.OperationMiddlewares["GetTestDBByID"]...)
	router.PUT(options.BaseURL+"/test_db/:test_id", wrapper.UpdateTestDB, options.OperationMiddlewares["UpdateTestDB"]...)
	router.PUT(options.BaseURL+"/users/:user_id/role", wrapper.AssignUserRole, options.OperationMiddlewares["AssignUserRole"]...)

}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Fxbc9u2Ev4rGJ7zyFhynGZaPx3fmriTnLpycvqQaDQQsaJQkwADgFbUjP77GVxI8QJKsqNb+hZHuHzY",
	"/Xax2F3pWxDxNOMMmJLB+bdARlNIsfnnRaQoZ++oVBd3twOQGWcS9AeZ4BkIRcEMizgx/wtfcZolEJwH",
	"9x+vrm7u74MwUPNM/4dUgrI4WIQBwQrrwVRBamb/W8AkOA/+1VvC6DkMPQug3HlRroeFwHP9dwpS4rix",
	"vcyjCKRsb78IAwFfciqABOefLPDlGg7csJzGx39BpPQ2DSAtEWDz+YiAjOpQ3oBCCqRC15cooVL5ROIm",
	"U1KbehoGEy5SrILzgDL1+tVyKmUKYhCVufaD2sY3H3x7ASMZp0zVB/c0xBEZr5XYEmpYO3MdSGUbrzCl",
	"pDH7KEEMeAID+JKDVG2ZCp7Ac4TSgFws40WSq+mVAAJMUZx0IsmwlDMuSINlEAlQpy/PggqocmgYpJS9",
	"AxaraXD+s0cTuQTBcNpQm6B/P9C1aijnhssNu86n5bx9811ptW7Xqt3uy06bW7dOCymmiUfm/3F/n0Q8",
	"rSrUjvdIYpInyaitwIFeDF1E0xQT3zRNx/oMrcyggyCO/yWaPKck2AGZrEVXaGVg+iR8JQArWGm4pZOQ",
	"NTifTsOXw3Dp+Dfwbk1vb2y57WQxSSlbe87lZN+5btJMzbdnJ16+E0hAAXkq371wheDiKVhvBoPR5cX1",
	"aHDzx8eb+w8bY6bsESeUIGG1jcaczLdxgF+5iLm6c96rk0tbMtcGPjvKB+st4ERN9+sv7Z4H8JaNjdvC",
	"Z491CAmPsNcZShCPNGoAnvIUZlw8eCcorPK6fwj4w9qzuWnLDUMD0ne4dzymbL+KNFseQI/1fT3+WO83",
	"UvwBmP67HRR+zagAOaKshvTsdb/v9cp6IU/IeQlY+K6yVgxZgVNbrYbEd9A7HFOG9e3yHqw66idNaErr",
	"oe2p9wRcEBCj8byO3wTB/vvVTiBUNC4eE/q2RmdNnZ/6xahw3bW9/GmjmN9MHOlN6gZ0tjYWziyRrJgK",
	"BPUFK8KpHtunjQFgQhlIuV8rK7c9gKWVe19NIXpoH9Z/7WOFx1gCijib0DgXhsGISpQJkMDUpg5SAN7g",
	"8nUzV8JfoS59MOs2CKEaKE7uaiM20o2Vz8KD4bsPFhYY/SeMqVT6AbDbgOLZ8f/RvSWX56g9AIpzr3xf",
	"DjR9yf9A0AmNsE2RHEkgp6GtDy/bzunVzy9Pf9FqSPHXQuSvawp47UurbItVDGYjP0UYzO6/hyVeyYWF",
	"76vt65UnT2DPft68Mffv4qvbrnnbfs9b1q4kt5gLpXKkF32si0iJHMqxY84TwOzpb+lw2+m4KoAqdJ9K",
	"7kEZ+lmJ7T3v0JUD9d9AH0Cq68v9mord8wDGYjd+R6U6RHmgfezvKw/o8euF3XiEbCY8t3S3DDtZrS1k",
	"pNxHLE8SPG6ZdUWPnct3qecp64flG2l9UrIhlmKiTwIfM3K4nOJWvKaGihX3P35b5zUB0/xG38A/SmSy",
	"Knpoq9RkhKJcUDW/11ZjjzQ2+YGLXEMt/vq12Pe3Pz8EoS0+GpE3cglTpbJgsTDJCqWD1OSaRyV/Bc00",
	"PYLz4A1Vb/MxGkDGJVVc6FdFLhK3gjzv9WKqpvlYH7tnBIFFv98rU1WaEGzC2wu/dSPQxd2tfrph9Iaj",
	"MY4egBEkHyABxRnKBNcSQOOcJgpNuECZ0OyKKIsRRnqBF1LNEyinYhFNqYJI5QJOPrNbhSiLkpyARDfR",
	"lCPBc0VZHKI7LlUs4P6Pd8hmUJCaCp7HU/Tm98H7EP325weEczUFplwsHiLN1p41HaRfoKSYGnGmBE9C",
	"dD/DcQyi93sG7OLuNkRGs+ixEtKHSL9SFSrCQzRJ+CxEAyBUvjAvN5RSQhKYYQEhSmlsH7gyRJgRdM2j",
	"BxBI5lnGhTr5zD4zpyRRKukcbaSdzyYwocqwuKqQIAweQUirqdOT/knfJG0yYDijwXlwdtI/OTOPGTU1",
	"pOlVoq8YjPlZE6ac3RJbt3Xhho5UnPM0w1/2+9Y+mQJbR8VZljhZ9f6SnC2r6JvFdM0Cu6F5nX12oK0g",
	"V60rOP9Ut6tPw8UwDGSepljMXf0ZJwnCj5gaz274i8ujKRzLZVIuGOrFe5pGvYlJ0L+oPkYyLj2iqmfy",
	"A+soQKpLTuZbk5S/XLCo+yXttBc7VFerRuTR1KBuK9pBIglMITpBagrOvqhEwmUqgGiuvtomzFptyIPx",
	"tl7TsYwqKeOE27R6F9eUhNF0q9Al4bFNH/tJYlLUO+KGv4q/Z260yg0euZsxqAg/jdZP96/1IsmD9O1U",
	"WG2dAhao9t6x9h/uuikS9t0M4LlaSQH9+YHt06I4mBI+Mi0rLujfQJ7myR3wKBdCu5MNlWJzgl1X3HvY",
	"6e3m6T7xiOTKncj0Qfw4+tA3a1SBjiaCp5uqpXD+3dZSJLJ35DObefKNvOXpvqmhhxzVRan3/2WP7Ky4",
	"ahs44MRG3PCVSiVbN7eVFGIwQ0VbUScDJTDyohroryJjM8+/M1p2FRSOMNSrwlwR6GXAiH7+1UR9bCGf",
	"Frvn7bcu6jMx4gZvhFo1Zofc+RFeCAVEG2Afmgnatfgi/TZBKiNmVE0tW2Dtw8DQaf6izEP5CVJJie2I",
	"Hp6k2xGS46Zigge88PR9Y1pxiMcd1Klh5Vq5pW00VOYR27SYmrazVXGpbUzbZWza7vPzZV2Wy5uUX0If",
	"m6c3fQ6oggPpQcyVF9zZ3YHt6UXRIrFKAGUfxS5l4O3fWS8G26yxCIOf+meHxsK4KvCsUYuoSNSvF564",
	"bn+vg1r2Pe/IP7Ubq/cckzcr/L7kFk8ARQbokWStNn2tWemahLjJa/DMtjYVD7YUZxllcVdG1JCj980V",
	"rxeGJrmHJctKlsk2C5yCAiENPMpMt4bxa7ZZp1oMr6k5rMhsfYF9uBtCtqtye74vNyVkboA6Qr7aHyHN",
	"5toDTXjOnpg9sMLdFh+r5QwvL+sdFD8+N/0dIUfKT6ecw/KUC4fjuYwdQJbgqDhNQVBT48SGx11cLb5b",
	"uCLcWbaRtKnZfDzFgFiejkGESCoslLSJt9OTILQ0/pKDKfs6Hrue56UsCUxwnijTvZRSRtM89XZoL8Lm",
	"5v81+yI+QYLP9MNeIL16185Fm7Vv674p47u9+/2nIrniSZ4yHWkTowHJhaIs7kJSaen2gKk0vgPTED5V",
	"/mfZHjL0NAU0cd1zoRChAgxJVsMhVHTgsW31BRb7V+OLWyWE4Q4N3NPd5H3Pm34gIJoVrkR7oNDIyBmV",
	"BvS8UrH5urIytWJN84pZF5Y8XIQro2Qrtx3FyfV2qT3HyO3mPq+/nS2D5GcEqXUFeOVf8au9b85YF9aI",
	"ElDQVsy1+f9SMeuv/6UH2OD67+gAGx66Fs9nqPjO5f4v3dlzb1qrq01oEK65US/nt9f/CG1vbHcEFKbJ",
	"j6Tt8hciSlWj8RxZCfv8bvez8xDWfRT+/QA8O1wsP/vOJ+eGt0suQcjeN/fjAIte8bsFXv7Vf9FjIwYu",
	"f3Xg6Bjo/32SIywW2PK4eWIayAfgo4HAHYpnEtPK270ikeIIt4rX5XvSfde8IJZt7e0Fi+Hi/wEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
